spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/fornecedor
    username: root
    password: root
  jpa:
#    hibernate:
#     ddl-auto: create
    show-sql: true
